### ISSUE TITLE
Can I get the number of player connected on a server ?

### ISSUE THREAD

**Issue by aonyx45** [tehbeard/node-rcon#7]
Hello, 

I've started to use your code and i was wondering : is there a way to get the number of player connected, the motd, etc etc.. using your node-rcon ?

Regards,

**Comment by tehbeard** [comment]
The number of players connected could be gotten by calling the list command through this library and then parsing the result.

But if you are also after the MOTD, I would advise using the query protocol instead, there are some links to some libraries to do with at the bottom of this link https://wiki.vg/Query
