### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Plagiatus** [tehbeard/node-rcon#8]
Hey there, I keep stumbling over this repo when I want to connect my MC Server through a node.js app. I did just notice however that this repo doesn't have a LICENSE, which prevents me from being able to use it in my projects. Is this intended? Because if not, adding a LICENSE would go a long way :)

**Comment by tehbeard** [comment]
Added a MIT License.
https://github.com/tehbeard/node-rcon/commit/5b634ae647d083d944c7fc4388f86be969789fb5
